name: CI
on:
  # schedule: [{cron: '0 0 * * *'}]
  pull_request:
  push:
    paths:
      - '**.agda'
      - '*.agda-lib'
      - '.github/workflows/**.yml'
    branches: [master]
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: omelkonian/setup-agda@v2.2
        with:
          agda-version: 2.7.0.1
          stdlib-version: 2.2
          libraries: agda/agda-stdlib-classes#v2.2
          main: standard-library-meta
          deploy: ${{ github.ref == 'refs/heads/master' }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ribbon: true
          measure-typechecking: true
